js:
  - content/snippets/js/s/*.md
  - content/collections/js/*.yaml
css:
  - content/snippets/css/s/*.md
  - content/collections/css/*.yaml
html:
  - content/snippets/html/s/*.md
  - content/collections/html/*.yaml
git:
  - content/snippets/git/s/*.md
  - content/collections/git/*.yaml
python:
  - content/snippets/python/s/*.md
  - content/collections/python/*.yaml
react:
  - content/snippets/react/s/*.md
  - content/collections/react/*.yaml
snippet:
  - content/snippets/**/*.md
collection:
  - content/collections/**/*.yaml
content:
  - content/**/*.md
  - content/**/*.yaml
