name: Deploy production (push)
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          web:
            - 'src/**'
            - 'astro.config.mjs'
            - 'netlify.toml'
            - 'package-lock.json'
            - 'package.json'
    # run only if 'web' files were changed
    - name: Run the Netlify build hook
      env:
        DEPLOY_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        DEPLOY_TRIGGER: ${{ github.event_name }}
      if: steps.filter.outputs.web == 'true'
      run: |
        chmod +x ./bin/deploy
        ./bin/deploy production
